### ISSUE TITLE
Check activity of all projects.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#70]
We need to check activity of all projects for all lists and if we have mammoth's shit in list then we need to remove this shit from this list.

We must remember that we do not leave **deprecated** projects on the list. 

The **maximum** term of the **last activity(issue updates, wiki edits, commits)** is **12 months**.

**Comment by TrueFurby** [comment]
Is **last commit** really the only *variable* that the projects should be measured by?

Maybe more activities could be included such as **last issue update**  or **wiki edits**?

**Comment by lk-geimfari** [comment]
@TrueFurby Of course, not. We'll removed from list only deprecated projects (if there are any.). Which are does not supported by maintainer. Only project without any activity.

**Comment by lk-geimfari** [comment]
@TrueFurby I just edited text of issue. Thanks for asking. So now we can avoid misunderstandings.

**Comment by sytranvn** [comment]
I created an issue for [Image of javascripts/socket.io is outdated](https://github.com/lk-geimfari/awesomo/issues/95) but found it's better to post the issue here.

[socket.io](https://socket.io/) has been upgraded to 2.0 few months ago but the package's image has v1.0 on it. We should remove the version part of that image and also add a rule to apply to all packages' image.
